(() => {
const $=id=>document.getElementById(id),L=window.Lattice,N=L.N,total=N*N,kick=L.kickTable(2),toyKick=[0,1,2,1,0,-1,-2,-1],mod=x=>(x%8+8)%8;
let phase=0,selected=10,scene=0,small=[],points=L.initialPoints(),initial=points.slice(),xs,ys,colors,step=0,dir=0,target=0,timer=null;
const scenes=[
 {label:'PREDICT',title:'Chaos can scramble. Must it forget?',prompt:'After 100 forward steps and 100 backward steps, which picture will come home exactly?',observation:'Two rules, the same starting image. Predict before pressing Intervene.',next:'Intervene →'},
 {label:'INTERVENE',title:'Scramble with 100 kicks and drifts.',prompt:'The lattice rounds its kick to a fixed table, then moves whole cells. The other rule uses floating-point arithmetic.',observation:'Watch the identities move. In the lattice, every occupied cell still has exactly one identity.',next:'Reveal →'},
 {label:'REVEAL',title:'Now undo the steps in reverse order.',prompt:'Undo each drift before its kick. Does reversing the rule recover every original identity?',observation:'Compare the counters. Zero exact-coordinate mismatches means every lattice identity returned in this run.',next:'Establish →'},
 {label:'ESTABLISH',title:'An exact inverse needs no lost information.',prompt:'Rounding a fixed rule can preserve every state. The 8×8 toy shows why; the proof has a separate boundary.',observation:'',next:'End'}
];
function stop(){clearInterval(timer);timer=null;dir=0}
function advance(direction){if(direction>0){L.fwd(points,kick);L.floatFwd(xs,ys,2);step++}else{L.bwd(points,kick);L.floatBwd(xs,ys,2);step--}}
function showScene(){const s=scenes[scene];document.body.setAttribute('data-scene-index',String(scene));document.body.setAttribute('data-scene-count',String(scenes.length));$('scene-label').textContent=`0${scene+1} / 04 · ${s.label}`;$('scene-title').textContent=s.title;$('scene-prompt').textContent=s.prompt;$('scene-observation').textContent=s.observation;$('scene-count').textContent=`${scene+1} / ${scenes.length}`;$('scene-prev').disabled=scene===0;$('scene-next').disabled=scene===scenes.length-1;$('scene-next').textContent=s.next;$('echo-panel').hidden=scene===3;$('establish-panel').hidden=scene!==3;}
function goScene(index){scene=Math.max(0,Math.min(scenes.length-1,index));reset();showScene();if(!colors)return;if(scene===1)run(1,100);if(scene>=2){for(let i=0;i<100;i++)advance(1);draw();if(scene===2)run(-1);else{for(let i=0;i<100;i++)advance(-1);draw()}}}
function resetPresentation(){phase=0;selected=10;$('steps').value='100';$('steps-out').textContent='100';$('experiment-controls').open=false;$('narration').open=false;toy();goScene(0)}
$('scene-next').onclick=()=>goScene(scene+1);$('scene-prev').onclick=()=>goScene(scene-1);$('scene-reset').onclick=resetPresentation;
for(const [id,action] of [['scene-next','next'],['scene-prev','back'],['scene-reset','reset']])$(id).setAttribute('data-action',action);
const phaseTitles=['Predict: where will the selected cell move?','1 · Kick: shift columns','2 · Drift: shift rows','3 · Undo drift: shift rows back','4 · Undo kick: every cell home'];
function toy(){small=Array.from({length:64},(_,id)=>({id,x:id%8,p:Math.floor(id/8)}));for(const v of small){if(phase>=1)v.p=mod(v.p+toyKick[v.x]);if(phase>=2)v.x=mod(v.x+v.p);if(phase>=3)v.x=mod(v.x-v.p);if(phase>=4)v.p=mod(v.p-toyKick[v.x])}const cells=[...small].sort((a,b)=>(a.p*8+a.x)-(b.p*8+b.x));$('grid').replaceChildren();for(const v of cells){const b=document.createElement('button');b.textContent=String(v.id).padStart(2,'0');b.style.background=`hsl(${175+(v.id%8)*8} 48% ${38+Math.floor(v.id/8)*4}%)`;b.setAttribute('aria-pressed',String(v.id===selected));b.setAttribute('aria-label',`Cell ${v.id}, now x ${v.x}, p ${v.p}`);b.onclick=()=>{selected=v.id;toy()};$('grid').append(b)}const v=small[selected];$('selected').textContent=`Cell ${selected}: origin (${selected%8}, ${Math.floor(selected/8)}) → now (${v.x}, ${v.p})`;const occupied=new Set(small.map(v=>v.x+8*v.p)).size;$('occupancy').textContent=`${occupied} distinct cells / 64 · ${64-occupied} lost cells`;$('phase-title').textContent=phaseTitles[phase];$('formula').textContent=['Every numbered cell has one home.','p ← p + kick[x] (mod 8)','x ← x + p (mod 8)','x ← x − p (mod 8)','p ← p − kick[x] (mod 8)'][phase];$('half-prev').disabled=phase===0;$('half-next').disabled=phase===4;}
$('half-next').onclick=()=>{phase=Math.min(4,phase+1);toy()};$('half-prev').onclick=()=>{phase=Math.max(0,phase-1);toy()};$('half-reset').onclick=()=>{phase=0;selected=10;toy()};
function reset(){stop();step=0;points=initial.slice();xs=new Float64Array(total);ys=new Float64Array(total);for(let i=0;i<total;i++){xs[i]=(points[2*i]+.5)/N;ys[i]=(points[2*i+1]+.5)/N}draw()}
function paint(id,position){const g=$(id).getContext('2d'),im=g.createImageData(N,N),d=im.data;for(let o=0;o<d.length;o+=4){d[o]=14;d[o+1]=25;d[o+2]=37;d[o+3]=255}for(let i=0;i<total;i++){const [x,p]=position(i),o=4*(((127-p+256)&255)*256+x);d[o]=colors[i*4];d[o+1]=colors[i*4+1];d[o+2]=colors[i*4+2]}g.putImageData(im,0,0)}
let badL=0,badF=0,distinct=total;
function draw(){if(!colors)return;badL=badF=0;const seen=new Uint8Array(total);distinct=0;for(let i=0;i<total;i++){if(points[i*2]!==initial[i*2]||points[i*2+1]!==initial[i*2+1])badL++;if((Math.floor(xs[i]*256)&255)!==initial[i*2]||(Math.floor(ys[i]*256)&255)!==initial[i*2+1])badF++;const cell=points[i*2]+256*points[i*2+1];if(!seen[cell]){seen[cell]=1;distinct++}}paint('exact',i=>[points[i*2],points[i*2+1]]);paint('float',i=>[Math.floor(xs[i]*256)&255,Math.floor(ys[i]*256)&255]);$('exact-count').textContent=`${badL.toLocaleString()} / 65,536 exact coordinate mismatches`;$('float-count').textContent=`${badF.toLocaleString()} / 65,536 cell mismatches (256×256 bins)`;$('exact-count').style.color=badL===0?'#5bddc1':'#ffbf67';$('distinct').textContent=`${distinct.toLocaleString()} distinct exact cells · ${total-distinct} lost cells`;$('echo-status').textContent=dir?`${dir>0?'Scrambling':'Returning'} · ${step} steps from home`:`${step} steps from home${step===0?' · compare the exact counts':''}`;$('result-summary').textContent=`This run: ${badL.toLocaleString()} exact-coordinate mismatches; ${badF.toLocaleString()} floating-point display-bin mismatches; ${step} steps from home.`;$('scramble').disabled=dir!==0;$('back').disabled=step===0||dir!==0;$('stop').disabled=dir===0;}
function run(direction,count=+$('steps').value){if(!colors||dir)return;dir=direction;target=direction>0?step+count:0;const fast=matchMedia('(prefers-reduced-motion: reduce)').matches;timer=setInterval(()=>{for(let j=0;j<(fast?200:2)&&step!==target;j++){advance(dir)}if(step===target){clearInterval(timer);timer=null;dir=0}draw()},16);draw()}
$('scramble').onclick=()=>run(1);$('back').onclick=()=>run(-1);$('stop').onclick=()=>{stop();draw()};$('reset').onclick=reset;$('steps').oninput=()=>{$('steps-out').textContent=$('steps').value};$('full').onclick=()=>{const target=document.fullscreenElement?document:document.documentElement,method=document.fullscreenElement?document.exitFullscreen:target.requestFullscreen;if(!method){$('full').textContent='Fullscreen unavailable';return}Promise.resolve(method.call(target)).catch(()=>{$('full').textContent='Fullscreen unavailable'})};
window.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.target.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if((k===' '||k==='enter')&&['BUTTON','SUMMARY','A'].includes(e.target.tagName))return;if(k==='arrowright'){e.preventDefault();$('scene-next').click()}if(k==='arrowleft'){e.preventDefault();$('scene-prev').click()}if(k==='s')run(1);if(k==='b')run(-1);if(k===' '){e.preventDefault();$('stop').click()}if(k==='r')resetPresentation();if(k==='f')$('full').click();if(k==='n'){const d=$('narration');d.open=!d.open}});
window.LatticeLive={run,reset,goScene,resetPresentation,toyState:()=>small.map(v=>({...v})),getState:()=>({scene,phase,selected,step,dir,badL,badF,distinct,ready:!!colors})};window.presentationState=()=>({...window.LatticeLive.getState(),steps:+$('steps').value,toy:window.LatticeLive.toyState()});toy();showScene();const image=new Image();image.onload=()=>{const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.drawImage(image,0,0);colors=g.getImageData(0,0,256,256).data;goScene(scene)};image.src=window.CAMEL_PNG;
})();
